### ISSUE TITLE
Missing source code

### ISSUE THREAD

**Issue by naveda89** [bertramdev/coffee-grails-asset-pipeline#9]
As i see the source code is missing since d001e15e17549055297ac562347451f149a8babc

Where can i find the it? Maybe removing it was a mistake?

Thx!! :smile:

**Comment by davydotcom** [comment]
Source code is no longer located in the grails adapter you want to look at the binary plugin that works for more than just grails now located at [https://github.com/bertramdev/coffee-asset-pipeline](https://github.com/bertramdev/coffee-asset-pipeline)

**Comment by naveda89** [comment]
Okay! Thx for the really fast reply :+1:
